### ISSUE TITLE
Update readme.md on howto setup sbt/java1.8 env

### ISSUE THREAD

**Issue by companycy** [cheerx/qingstor-sdk-scala#1]
在搭建环境过程中, sbt/java1.8 是必须的, 特补上相关的步骤到Readme.md里. 

1. install sbt on ubuntu
echo "deb https://dl.bintray.com/sbt/debian /" | sudo tee -a /etc/apt/sources.list.d/sbt.list
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 2EE0EA64E40A89B84B2DF73499E82A75642AC823
sudo apt-get update
sudo apt-get install sbt

2. update java to 1.8
sudo add-apt-repository ppa:openjdk-r/ppa
sudo apt-get update
sudo apt-get install openjdk-8-jre
sudo update-alternatives --config java

然后运行sbt run就可以了. 稍后会补上patch for Readme.md.

**Comment by cheerx** [comment]
已更新，谢谢
