### ISSUE TITLE
It takes a long time to download dependencies

### ISSUE THREAD

**Issue by companycy** [cheerx/qingstor-sdk-scala#3]
It really takes a long time... I have to manually download jar using wget. And 2 versions of akka jar are downloaded: 2.11/2.12, which should be unnecessary.

I guess it may be due to below config in build.sbt:
crossScalaVersions := Seq("2.12.1", "2.11.0")

**Comment by cheerx** [comment]
Scala 2.11 and 2.12 is not binary compatible, and we will support the latest two version of Scala, so we have to cross compile between 2.12 and 2.11

**Comment by cheerx** [comment]
Reopen this issue if this question is still unclear
